# Generated by Django 3.2.7 on 2021-10-11 05:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_data',
        ),
        migrations.AddField(
            model_name='post',
            name='created_data',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 5, 34, 39, 268705, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 5, 34, 39, 269454, tzinfo=utc)),
        ),
    ]
