# Generated by Django 3.2.7 on 2021-10-11 05:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211011_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_data',
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 5, 38, 15, 511282, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 5, 38, 15, 511984, tzinfo=utc)),
        ),
    ]
